---
title: "Monthly Zoom Account Utilization Report"
author: "Shambhala Global Services"
output: pdf_document
---

Uses data generated by: get-individual-history-data.R

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Overview

```{r, echo=FALSE, message=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(knitr))
library(gt)
library(here)
library(patchwork)
pagebreak <- function() {
  if (knitr::is_latex_output())
    return("\\newpage")
  else
    return('<div style="page-break-before: always;" />')
}
theme_set(theme_light())
```


```{r, echo=FALSE, message=FALSE}
big_meeting_cut_off <- 50

year <- "2020"
mon_start <- 1
mon_end <- 5 
file_list <- paste0("meetings_", 
                    sprintf("%s-%02.f", year, seq(mon_start, mon_end)),
                    ".Rds")
month_range <- paste0(sprintf("%s-%02.f", year, mon_start), " and ", 
                      sprintf("%s-%02.f", year, mon_end))
file_list
month_range
save_file_tag <- paste0(year, "_", mon_start, "_", mon_end)

meetings_in_quarter <- file_list %>% map_df(function(x) read_rds(here("data", x)))
```


```{r , echo=FALSE, message=FALSE}
large_meetings <- meetings_in_quarter %>% 
  filter(participants_count >= big_meeting_cut_off) %>% 
  mutate(Date = as.Date(start_time)) %>% 
  select(Date, Topic = topic, 
         Participants = participants_count)

large_meetings %>% 
  # DT::datatable()
  kable()

large_meetings
```


```{r , echo=FALSE, message=FALSE}
gt_table <- large_meetings %>% 
  gt() %>% 
  tab_header(title = paste0("Large meetings between ", month_range)) %>% 
  cols_align(align = "right", columns = "Participants")

gt_table
 gtsave(gt_table, here::here("img", paste0(save_file_tag, "big_events_table", save_file_tag, ".png")))
gt_table 
```

```{r}
meetings_in_quarter <- meetings_in_quarter %>% 
  filter(!is.na(weekday)) %>% 
  mutate(start_hour = hour(start_time),
         meeting_size = if_else(participants_count > big_meeting_cut_off, "Big", "Smaller")) 
  
```

```{r}
n_weekday <- meetings_in_quarter %>% 
  ggplot(aes(weekday)) +
  geom_bar() +
  labs(title = "Number of meetings",
       subtitle = paste0("By day of week between ", month_range),
       y = NULL, x = NULL) +
  facet_wrap(~ meeting_size) 

n_weekday  
```


```{r}
size_weekday <- meetings_in_quarter %>% 
  ggplot(aes(weekday, participants_count)) +
  geom_jitter() +
  labs(title = paste0("Meeting participants by week day between ", month_range),
       y = NULL, x = NULL) +
  # facet_wrap(~ meeting_size) +
  scale_y_log10()
 
size_weekday 

ggsave(here::here("img", paste0("size_weekday", "_time.png")))
```

```{r}
count_by_hour <- meetings_in_quarter %>% 
  ggplot(aes(start_hour, participants_count)) +
  geom_col() +
  labs(title = "Total participants",
                      subtitle = paste0("by hour of day between ", month_range),
       y = NULL, x = "GMT") +
  facet_grid(~ meeting_size)
 
count_by_hour 
```
paste the two plots together
```{r}

patched <- (n_weekday /  count_by_hour)
patched + plot_annotation(
  caption = paste0("'Big' means more than ", big_meeting_cut_off, " participants" )
)
```

```{r}
ggsave(here::here("img", paste0(save_file_tag, "_time.png")))

```

```{r , echo=FALSE, message=FALSE}
months_list <- paste0(sprintf("%s-%02.f", year, seq(mon_start, mon_end)))


gt_print <- function(x) {
  df <- read_rds(here("data", paste0("meetings_", x, ".Rds"))) 
    
    df <- df %>% 
       filter(participants_count >= big_meeting_cut_off)
    df <- df %>% 
      mutate(Date = as.Date(start_time)) %>% 
  select(Date, Topic = topic, 
         Participants = participants_count)
    
gt_table <-   gt(df) %>% 
  tab_header(title = paste0("Large meetings - ", x)) %>% 
  cols_align(align = "right", columns = "Participants")

# gt_table
 gtsave(gt_table, here::here("img", paste0(x, "big_events_table", save_file_tag, ".png")))

}

map(months_list, gt_print)
```


```{r , echo=FALSE, message=FALSE}


  gt_table <- file %>% 
  gt() %>% 
  tab_header(title = paste0("Large meetings between ", month_range)) %>% 
  cols_align(align = "right", columns = "Participants")

gt_table
 gtsave(gt_table, here::here("img", paste0(save_file_tag, "big_events_table", save_file_tag, ".png")))
gt_table }
```

```

